matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode8

cache:
  directories:
    - $HOME/.nvm
    - $HOME/.npm
    - $HOME/.cocoapods
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - example/node_modules

before_cache: .travis/before-cache.sh
before_install: . .travis/before-install.sh
install: .travis/install.sh
before_script: .travis/before-ci.sh
script: .travis/ci.sh
